In [3]:
import numpy as np

list_numbers = [[12, 23, -45], [18, -77, -44]]
a = np.array(list_numbers)

print(a[a>=0])

[12 23 18]


In [6]:
print(a*2)

[[  24   46  -90]
 [  36 -154  -88]]


In [8]:
print(np.sum(a, axis=1))

[ -10 -103]


In [10]:
print(np.sum(a, axis=0))

[ 30 -54 -89]


In [16]:
b = np.arange(0, 100)
b = b.reshape(2, 5, 10)
print(b)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [21]:
print(b[1, 0, :])

[50 51 52 53 54 55 56 57 58 59]


In [26]:
print(sum(a[0]>a[1]))

1
